version: "3"
services:
#
# Proxy
#
  proxy:
    image: og-proxy--${PROJECT_ID}
    container_name: og-proxy--${PROJECT_ID}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      og-proxy-network--${PROJECT_ID}:
      og-local-network--${PROJECT_ID}:
        ipv4_address: 172.0.0.3
    working_dir: /var/ogproxy
    env_file:
      - .project.env
      - .docker.env
    environment:
      CONTAINER_ROLE: proxy
      NGINX_UNAME: www-data
      APP_ROOT: /var/ogproxy
      SSH_AUTH_SOCK: /ssh-agent
      SSL_CERT_FILE: /etc/ssl/mkcert/rootCA.pem
      SSL_CERT_DIR: /etc/ssl/mkcert
      PROJECT_ID: ${PROJECT_ID}
    volumes:
      - .:/var/ogproxy
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/conf:/etc/nginx/conf
      - $SSH_AUTH_SOCK:/ssh-agent:ro
      # - ./nginx:/var/log/nginx
    ports:
      - 443:443
      - 80:80
# END
# Proxy
# END
#
# Drupal
#
  drupal:
    image: og-drupal--${PROJECT_ID}
    container_name: og-drupal--${PROJECT_ID}
    build:
      context: .
      dockerfile: docker/drupal/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /var/www/html
    networks:
      og-proxy-network--${PROJECT_ID}:
      og-local-network--${PROJECT_ID}:
        ipv4_address: 172.0.0.6
    depends_on:
      proxy:
        condition: service_healthy
      postgres:
        condition: service_started
      solr:
        condition: service_healthy
    links:
      - proxy
      - postgres
      - solr
    env_file:
      - .project.env
      - .docker.env
    environment:
      CONTAINER_ROLE: drupal
      PGHOST: postgres
      PGDATABASE: og_drupal_local__${PROJECT_ID}
      PGUSER: homestead
      PGPASSWORD: secret
      SSH_AUTH_SOCK: /ssh-agent
      PATH: '$PATH:/var/www/html/drupal/vendor/bin'
      NGINX_UNAME: www-data
      APP_ROOT: /var/www/html
      SSL_CERT_FILE: /etc/ssl/mkcert/rootCA.pem
      SSL_CERT_DIR: /etc/ssl/mkcert
      PROJECT_ID: ${PROJECT_ID}
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/conf:/etc/nginx/conf
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/var/www/html/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent:ro
      # - ./nginx:/var/log/nginx
    ports:
      - 4430:4430
# END
# Drupal
# END
#
# CKAN Registry
#
  ckan:
    container_name: og-ckan-registry--${PROJECT_ID}
    image: og-ckan-registry--${PROJECT_ID}
    build:
      context: .
      dockerfile: docker/ckan/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    healthcheck:
      test: /srv/app/ckan/registry/bin/uwsgi --connect-and-read 127.0.0.1:1717 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /srv/app
    networks:
      og-proxy-network--${PROJECT_ID}:
      og-local-network--${PROJECT_ID}:
        ipv4_address: 172.0.0.7
    depends_on:
      proxy:
        condition: service_healthy
      postgres:
        condition: service_started
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - proxy
      - postgres
      - solr
    env_file:
      - .project.env
      - .docker.env
    environment:
      CONTAINER_ROLE: ckan
      CKAN_ROLE: registry
      PGHOST: postgres
      PGDATABASE: postgres
      PGUSER: homestead
      PGPASSWORD: secret
      SSH_AUTH_SOCK: /ssh-agent
      NGINX_UNAME: ckan
      APP_ROOT: /srv/app
      PATH: '$PATH:/srv/app/ckan/registry/bin'
      PY_VERSION: 2.7
      PIP_VERSION: 19.2.1
      SETUP_TOOLS_VERSION: 36.1
      WET_VERSION: v4.0.31
      GCWEB_VERSION: v5.1
      PYTHONHTTPSVERIFY: 0
      SSL_VERIFY: 0
      PORTAL_CONFIG: /srv/app/ckan/portal/portal.ini
      REGISTRY_CONFIG: /srv/app/ckan/registry/registry.ini
      CKAN_INI: /srv/app/ckan/registry/registry.ini
      DATA_URI: https://open.canada.ca/data
      PROJECT_ID: ${PROJECT_ID}
    volumes:
      - ./docker/config/ckan:/docker-entrypoint.d
      - .:/srv/app
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/ckan/wsgi:/etc/ckan/registry
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/srv/app/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent:ro
    ports:
      - 5001:5001
# END
# CKAN Registry
# END
#
# CKAN Portal
#
  ckanapi:
    container_name: og-ckan-portal--${PROJECT_ID}
    image: og-ckan-portal--${PROJECT_ID}
    build:
      context: .
      dockerfile: docker/ckan/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    healthcheck:
      test: /srv/app/ckan/portal/bin/uwsgi --connect-and-read 127.0.0.1:1717 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /srv/app
    networks:
      og-proxy-network--${PROJECT_ID}:
      og-local-network--${PROJECT_ID}:
        ipv4_address: 172.0.0.8
    depends_on:
      proxy:
        condition: service_healthy
      postgres:
        condition: service_started
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - proxy
      - postgres
      - solr
    env_file:
      - .project.env
      - .docker.env
    environment:
      CONTAINER_ROLE: ckan
      CKAN_ROLE: portal
      PGHOST: postgres
      PGDATABASE: postgres
      PGUSER: homestead
      PGPASSWORD: secret
      SSH_AUTH_SOCK: /ssh-agent
      NGINX_UNAME: ckan
      APP_ROOT: /srv/app
      PATH: '$PATH:/srv/app/ckan/portal/bin'
      PY_VERSION: 2.7
      PIP_VERSION: 19.2.1
      SETUP_TOOLS_VERSION: 36.1
      WET_VERSION: v4.0.31
      GCWEB_VERSION: v5.1
      PYTHONHTTPSVERIFY: 0
      SSL_VERIFY: 0
      PORTAL_CONFIG: /srv/app/ckan/portal/portal.ini
      REGISTRY_CONFIG: /srv/app/ckan/registry/registry.ini
      CKAN_INI: /srv/app/ckan/portal/portal.ini
      DATA_URI: https://open.canada.ca/data
      PROJECT_ID: ${PROJECT_ID}
    volumes:
      - ./docker/config/ckan:/docker-entrypoint.d
      - .:/srv/app
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/ckan/wsgi:/etc/ckan/portal
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/srv/app/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent:ro
    ports:
      - 5002:5002
# END
# CKAN Portal
# END
#
# Postgres
#
  postgres:
    container_name: og-postgres--${PROJECT_ID}
    image: og-postgres--${PROJECT_ID}
    restart: always
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      og-local-network--${PROJECT_ID}:
        ipv4_address: 172.0.0.9
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./docker/config/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
      PROJECT_ID: ${PROJECT_ID}
    env_file:
      - .project.env
      - .docker.env
    user: "${USER_ID:-0}:${GROUP_ID:-0}"
    ports:
      - 15438:5432
# END
# Postgres
# END
#
# Solr
#
  solr:
    container_name: og-solr--${PROJECT_ID}
    image: og-solr--${PROJECT_ID}
    restart: always
    build:
      context: .
      dockerfile: docker/solr/Dockerfile
    healthcheck:
      test: solr status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /opt/solr
    networks:
      og-proxy-network--${PROJECT_ID}:
      og-local-network--${PROJECT_ID}:
        ipv4_address: 172.0.0.10
    depends_on:
      proxy:
        condition: service_healthy
    links:
      - proxy
    volumes:
      # Persisting CKAN Solr Cores
      - ./solr/ckan_registry:/var/solr/data/ckan_registry
      - ./solr/ckan_portal:/var/solr/data/ckan_portal
      - ./solr/core_ati:/var/solr/data/core_ati
      - ./solr/core_contracts:/var/solr/data/core_contracts
      - ./solr/core_grants:/var/solr/data/core_grants
      - ./solr/core_hospitalityq:/var/solr/data/core_hospitalityq
      - ./solr/core_inventory:/var/solr/data/core_inventory
      - ./solr/core_reclassification:/var/solr/data/core_reclassification
      - ./solr/core_travela:/var/solr/data/core_travela
      - ./solr/core_travelq:/var/solr/data/core_travelq
      - ./solr/core_wrongdoing:/var/solr/data/core_wrongdoing
      # Persisting Django Solr Cores
      - ./solr/core_od_search:/var/solr/data/core_od_search
      - ./solr/core_bn_search:/var/solr/data/core_bn_search
      - ./solr/core_ati_search:/var/solr/data/core_ati_search
      - ./solr/core_ei_search:/var/solr/data/core_ei_search
      - ./solr/core_ct_search:/var/solr/data/core_ct_search
      - ./solr/core_gc_search:/var/solr/data/core_gc_search
      - ./solr/core_ap_search:/var/solr/data/core_ap_search
      - ./solr/core_sv_search:/var/solr/data/core_sv_search
      - ./solr/core_qp_search:/var/solr/data/core_qp_search
      - ./solr/core_sd_search:/var/solr/data/core_sd_search
      # Persisting Drupal Solr Cores
      - ./solr/drupal_content:/var/solr/data/drupal_content
      # Base Solr Cores
      - ./docker/config/solr/cores:/var/solr/local_data
    environment:
      CONTAINER_ROLE: solr
      NGINX_UNAME: root
      SOLR_SSL_ENABLED: "false"
      PROJECT_ID: ${PROJECT_ID}
    env_file:
      - .project.env
      - .docker.env
    user: "root:root"
    ports:
      - 8981:8983
# END
# Solr
# END
#
# Redis
#
  redis:
    container_name: og-redis--${PROJECT_ID}
    image: og-redis--${PROJECT_ID}
    restart: always
    healthcheck:
      test: redis-cli info server || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /data
    networks:
      og-proxy-network--${PROJECT_ID}:
      og-local-network--${PROJECT_ID}:
        ipv4_address: 172.0.0.11
    volumes:
      # - ./redis:/data
    environment:
      CONTAINER_ROLE: redis
      NGINX_UNAME: root
      PROJECT_ID: ${PROJECT_ID}
    env_file:
      - .project.env
      - .docker.env
    user: "root:root"
    ports:
      - 6979:6379
# END
# Redis
# END
#
# Django
#
  django:
    image: og-search--${PROJECT_ID}
    container_name: og-search--${PROJECT_ID}
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    healthcheck:
      test: /var/ocs/django/bin/uwsgi --connect-and-read 127.0.0.1:1717 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /var/ocs
    networks:
      og-proxy-network--${PROJECT_ID}:
      og-local-network--${PROJECT_ID}:
        ipv4_address: 172.0.0.12
    depends_on:
      proxy:
        condition: service_healthy
      postgres:
        condition: service_started
      solr:
        condition: service_healthy
    links:
      - proxy
      - postgres
      - solr
    env_file:
      - .project.env
      - .docker.env
    environment:
      CONTAINER_ROLE: search
      PGHOST: postgres
      PGDATABASE: postgres
      PGUSER: homestead
      PGPASSWORD: secret
      SSH_AUTH_SOCK: /ssh-agent
      PATH: '$PATH:/usr/local/lib'
      NGINX_UNAME: www-data
      APP_ROOT: /var/ocs
      PY_VERSION: 3.7
      WET_VERSION: v4.0.31
      CDTS_VERSION: v4_0_28
      CDTS_GCWEB_VERSION: v4_0_31
      GCWEB_VERSION: v5.1
      PYTHONHTTPSVERIFY: 0
      SSL_VERIFY: 0
      PROJECT_ID: ${PROJECT_ID}
    volumes:
      - .:/var/ocs
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/var/ocs/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent:ro
    ports:
      - 8080:8080
# END
# Django
# END

volumes:
  postgres:
    driver: "local"
  solr:
    driver: "local"

networks:
  og-proxy-network--${PROJECT_ID}:
    external : true
  og-local-network--${PROJECT_ID}:
    external : false
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.1