version: "3"
services:
#
# Proxy
#
  proxy:
    image: og-proxy
    container_name: og-proxy
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      og-proxy-network:
      og-local-network:
        ipv4_address: 172.0.0.3
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: proxy
      NGINX_UNAME: www-data
      SSH_AUTH_SOCK: /ssh-agent
      SSL_CERT_FILE: /etc/ssl/mkcert/rootCA.pem
      SSL_CERT_DIR: /etc/ssl/mkcert
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/certs:/usr/share/certs
      - $SSH_AUTH_SOCK:/ssh-agent:ro
      - $CA_LOCAL_ROOT:/etc/ssl/mkcert:ro
      # - ./nginx:/var/log/nginx
    ports:
      - 443:443
      - 80:80
# END
# Proxy
# END
#
# Drupal
#
  drupal:
    image: og-drupal
    container_name: og-drupal
    build:
      context: .
      dockerfile: docker/drupal/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /var/www/html
    networks:
      og-proxy-network:
      og-local-network:
        ipv4_address: 172.0.0.6
    depends_on:
      proxy:
        condition: service_healthy
      postgres:
        condition: service_started
      solr:
        condition: service_healthy
    links:
      - proxy
      - postgres
      - solr
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: drupal
      PGHOST: postgres
      PGDATABASE: og_drupal_local
      PGUSER: homestead
      PGPASSWORD: secret
      SSH_AUTH_SOCK: /ssh-agent
      PATH: '$PATH:/var/www/html/drupal/vendor/bin'
      NGINX_UNAME: www-data
      APP_ROOT: /var/www/html
      SSL_CERT_FILE: /etc/ssl/mkcert/rootCA.pem
      SSL_CERT_DIR: /etc/ssl/mkcert
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx/certs:/usr/share/certs
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/var/www/html/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent:ro
      - $CA_LOCAL_ROOT:/etc/ssl/mkcert:ro
      # - ./nginx:/var/log/nginx
    ports:
      - 4430:4430
# END
# Drupal
# END
#
# CKAN Registry
#
  ckan:
    container_name: og-ckan-registry
    image: openknowledge/ckan-base:2.8
    build:
      context: .
      dockerfile: docker/ckan/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    healthcheck:
      test: /srv/app/ckan/registry/bin/uwsgi --connect-and-read 127.0.0.1:1717 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /srv/app
    networks:
      og-proxy-network:
      og-local-network:
        ipv4_address: 172.0.0.7
    depends_on:
      proxy:
        condition: service_healthy
      postgres:
        condition: service_started
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - proxy
      - postgres
      - solr
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: ckan
      CKAN_ROLE: registry
      PGHOST: postgres
      PGDATABASE: postgres
      PGUSER: homestead
      PGPASSWORD: secret
      SSH_AUTH_SOCK: /ssh-agent
      NGINX_UNAME: ckan
      APP_ROOT: /srv/app
      PATH: '$PATH:/srv/app/ckan/registry/bin'
      PY_VERSION: 2.7
      PIP_VERSION: 19.2.1
      SETUP_TOOLS_VERSION: 36.1
      WET_VERSION: v4.0.31
      GCWEB_VERSION: v5.1
      PYTHONHTTPSVERIFY: 0
      SSL_CERT_FILE: /etc/ssl/mkcert/rootCA.pem
      SSL_CERT_DIR: /etc/ssl/mkcert
      SSL_VERIFY: 0
      PORTAL_CONFIG: /srv/app/ckan/portal/portal.ini
      REGISTRY_CONFIG: /srv/app/ckan/registry/registry.ini
      CKAN_INI: /srv/app/ckan/registry/registry.ini
      DATA_URI: https://open.canada.ca/data
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
    volumes:
      - ./docker/config/ckan:/docker-entrypoint.d
      - .:/srv/app
      - ./docker/config/nginx/certs:/usr/share/certs
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/ckan/apache:/etc/apache2/sites-available
      - ./docker/config/ckan/apache/registry.apache2.conf:/etc/apache2/apache2.conf
      - ./docker/config/ckan/apache/ports.conf:/etc/apache2/ports.conf
      - ./docker/config/ckan/wsgi:/etc/ckan/registry
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/srv/app/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent:ro
      - $CA_LOCAL_ROOT:/etc/ssl/mkcert:ro
    ports:
      - 5001:5001
# END
# CKAN Registry
# END
#
# CKAN Portal
#
  ckanapi:
    container_name: og-ckan-portal
    image: openknowledge/ckan-base:2.8
    build:
      context: .
      dockerfile: docker/ckan/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    healthcheck:
      test: /srv/app/ckan/portal/bin/uwsgi --connect-and-read 127.0.0.1:1717 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /srv/app
    networks:
      og-proxy-network:
      og-local-network:
        ipv4_address: 172.0.0.8
    depends_on:
      proxy:
        condition: service_healthy
      postgres:
        condition: service_started
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - proxy
      - postgres
      - solr
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: ckan
      CKAN_ROLE: portal
      PGHOST: postgres
      PGDATABASE: og_ckan_local
      PGUSER: homestead
      PGPASSWORD: secret
      SSH_AUTH_SOCK: /ssh-agent
      NGINX_UNAME: ckan
      APP_ROOT: /srv/app
      PATH: '$PATH:/srv/app/ckan/portal/bin'
      PY_VERSION: 2.7
      PIP_VERSION: 19.2.1
      SETUP_TOOLS_VERSION: 36.1
      WET_VERSION: v4.0.31
      GCWEB_VERSION: v5.1
      PYTHONHTTPSVERIFY: 0
      SSL_CERT_FILE: /etc/ssl/mkcert/rootCA.pem
      SSL_CERT_DIR: /etc/ssl/mkcert
      SSL_VERIFY: 0
      PORTAL_CONFIG: /srv/app/ckan/portal/portal.ini
      REGISTRY_CONFIG: /srv/app/ckan/registry/registry.ini
      CKAN_INI: /srv/app/ckan/portal/portal.ini
      DATA_URI: https://open.canada.ca/data
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
    volumes:
      - ./docker/config/ckan:/docker-entrypoint.d
      - .:/srv/app
      - ./docker/config/nginx/certs:/usr/share/certs
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/ckan/apache:/etc/apache2/sites-available
      - ./docker/config/ckan/apache/portal.apache2.conf:/etc/apache2/apache2.conf
      - ./docker/config/ckan/apache/ports.conf:/etc/apache2/ports.conf
      - ./docker/config/ckan/wsgi:/etc/ckan/portal
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/srv/app/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent:ro
      - $CA_LOCAL_ROOT:/etc/ssl/mkcert:ro
    ports:
      - 5002:5002
# END
# CKAN Portal
# END
#
# Postgres
#
  postgres:
    container_name: og-postgres
    image: postgres:9.6
    restart: always
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      og-local-network:
        ipv4_address: 172.0.0.9
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./docker/config/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: og_drupal_local
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .docker.env
    user: "${USER_ID:-0}:${GROUP_ID:-0}"
    ports:
      - 15438:5432
# END
# Postgres
# END
#
# Solr
#
  solr:
    container_name: og-solr
    image: solr
    restart: always
    build:
      context: .
      dockerfile: docker/solr/Dockerfile
    healthcheck:
      test: solr status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /opt/solr
    networks:
      og-proxy-network:
      og-local-network:
        ipv4_address: 172.0.0.10
    depends_on:
      proxy:
        condition: service_healthy
    links:
      - proxy
    volumes:
      - ./docker/config/solr/certs:/opt/solr/server/certs
      - ./docker/config/solr/certs/solr.p12:/etc/solr.p12
      - ./docker/config/nginx/certs:/usr/share/certs
      - ./solr/ckan_registry:/var/solr/data/ckan_registry
      - ./solr/ckan_portal:/var/solr/data/ckan_portal
      - ./solr/core_ati:/var/solr/data/core_ati
      - ./solr/core_contracts:/var/solr/data/core_contracts
      - ./solr/core_grants:/var/solr/data/core_grants
      - ./solr/core_hospitalityq:/var/solr/data/core_hospitalityq
      - ./solr/core_inventory:/var/solr/data/core_inventory
      - ./solr/core_reclassification:/var/solr/data/core_reclassification
      - ./solr/core_travela:/var/solr/data/core_travela
      - ./solr/core_travelq:/var/solr/data/core_travelq
      - ./solr/core_wrongdoing:/var/solr/data/core_wrongdoing
      - ./solr/drupal_content:/var/solr/data/drupal_content
      - ./docker/config/solr/cores:/var/solr/local_data
    environment:
      - CONTAINER_ROLE=solr
      - NGINX_UNAME=root
      - SOLR_SSL_ENABLED=true
      - SOLR_SSL_KEY_STORE=/etc/solr.p12
      - SOLR_SSL_KEY_STORE_PASSWORD=changeit
      - SOLR_SSL_TRUST_STORE=/etc/solr.p12
      - SOLR_SSL_TRUST_STORE_PASSWORD=changeit
      - SOLR_SSL_NEED_CLIENT_AUTH=false
      - SOLR_SSL_WANT_CLIENT_AUTH=false
      - SOLR_SSL_CHECK_PEER_NAME=true
      - SOLR_SSL_KEY_STORE_TYPE=PKCS12
      - SOLR_SSL_TRUST_STORE_TYPE=PKCS12
    user: "root:root"
    ports:
      - 8981:8983
# END
# Solr
# END
#
# Redis
#
  redis:
    container_name: og-redis
    image: redis
    restart: always
    healthcheck:
      test: redis-cli info server || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /data
    networks:
      og-proxy-network:
      og-local-network:
        ipv4_address: 172.0.0.11
    volumes:
      - ./docker/config/nginx/certs:/usr/share/certs
      # - ./redis:/data
    environment:
      - CONTAINER_ROLE=redis
      - NGINX_UNAME=root
    user: "root:root"
    ports:
      - 6979:6379
# END
# Redis
# END
#
# Django
#
  django:
    image: og-search
    container_name: og-search
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    healthcheck:
      test: netstat -ano | grep "8000" || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    working_dir: /var/ocs
    networks:
      og-proxy-network:
      og-local-network:
        ipv4_address: 172.0.0.12
    depends_on:
      proxy:
        condition: service_healthy
      postgres:
        condition: service_started
      solr:
        condition: service_healthy
    links:
      - proxy
      - postgres
      - solr
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: search
      PGHOST: postgres
      PGDATABASE: postgres
      PGUSER: homestead
      PGPASSWORD: secret
      SSH_AUTH_SOCK: /ssh-agent
      PATH: '$PATH:/usr/local/lib'
      NGINX_UNAME: www-data
      APP_ROOT: /var/ocs
      SSL_CERT_FILE: /etc/ssl/mkcert/rootCA.pem
      SSL_CERT_DIR: /etc/ssl/mkcert
    volumes:
      - .:/var/ocs
      - ./docker/config/nginx/certs:/usr/share/certs
      - ~/.gitconfig:/etc/gitconfig:ro
      - ~/.ssh:/var/ocs/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent:ro
      - $CA_LOCAL_ROOT:/etc/ssl/mkcert:ro
    ports:
      - 8080:8080
# END
# Django
# END

volumes:
  postgres:
    driver: "local"
  solr:
    driver: "local"

networks:
  og-proxy-network:
    external : true
  og-local-network:
    external : false
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.1