## traefik.yml

# log default is ERROR, but WARN is more helpful
log:
  level: WARN

# enable dashboard on 8080 with auth
api:
  insecure: true
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    exposedByDefault: false
    watch: true
  # file:
  #   fileName: /etc/traefik/traefik.yaml
  #   watch: true

# listen on 80/443, and redirect all 80 to 443 via 301
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

tls:
  certificates:
    - certFile: /usr/share/certs/open.local.pem
      keyFile: /usr/share/certs/open.local-key.pem